### ISSUE TITLE
Unicode all the things

### ISSUE THREAD

**Issue by mattbasta** [erikrose/parsimonious#33]
I'm assuming that this shouldn't happen so [I'mma filin' an issue](http://www.youtube.com/watch?v=dERZjJ9anbc)

```
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    stylesheet = do_parse(inp.read())
  File "/cygdrive/e/opt/crass/parse.py", line 411, in do_parse
    tree = css.parse(raw)
  File "/home/basta/.virtualenvs/crass/lib/python2.7/site-packages/parsimonious/grammar.py", line 83, in parse
    return self.default_rule.parse(text, pos=pos)
  File "/home/basta/.virtualenvs/crass/lib/python2.7/site-packages/parsimonious/expressions.py", line 40, in parse
    node = self.match(text, pos=pos)
  File "/home/basta/.virtualenvs/crass/lib/python2.7/site-packages/parsimonious/expressions.py", line 55, in match
    node = self._match(text, pos, {}, error)
  File "/home/basta/.virtualenvs/crass/lib/python2.7/site-packages/parsimonious/expressions.py", line 94, in _match
    error)
  File "/home/basta/.virtualenvs/crass/lib/python2.7/site-packages/parsimonious/expressions.py", line 230, in _uncached_match
    node = m._match(text, new_pos, cache, error)
  File "/home/basta/.virtualenvs/crass/lib/python2.7/site-packages/parsimonious/expressions.py", line 94, in _match
    error)
  File "/home/basta/.virtualenvs/crass/lib/python2.7/site-packages/parsimonious/expressions.py", line 230, in _uncached_match
    node = m._match(text, new_pos, cache, error)
  File "/home/basta/.virtualenvs/crass/lib/python2.7/site-packages/parsimonious/expressions.py", line 94, in _match
    error)
  File "/home/basta/.virtualenvs/crass/lib/python2.7/site-packages/parsimonious/expressions.py", line 307, in _uncached_match
    node = self.members[0]._match(text, pos, cache, error)
  File "/home/basta/.virtualenvs/crass/lib/python2.7/site-packages/parsimonious/expressions.py", line 94, in _match
    error)
  File "/home/basta/.virtualenvs/crass/lib/python2.7/site-packages/parsimonious/expressions.py", line 230, in _uncached_match
    node = m._match(text, new_pos, cache, error)
  File "/home/basta/.virtualenvs/crass/lib/python2.7/site-packages/parsimonious/expressions.py", line 94, in _match
    error)
  File "/home/basta/.virtualenvs/crass/lib/python2.7/site-packages/parsimonious/expressions.py", line 252, in _uncached_match
    node = m._match(text, pos, cache, error)
  File "/home/basta/.virtualenvs/crass/lib/python2.7/site-packages/parsimonious/expressions.py", line 94, in _match
    error)
  File "/home/basta/.virtualenvs/crass/lib/python2.7/site-packages/parsimonious/expressions.py", line 230, in _uncached_match
    node = m._match(text, new_pos, cache, error)
  File "/home/basta/.virtualenvs/crass/lib/python2.7/site-packages/parsimonious/expressions.py", line 94, in _match
    error)
  File "/home/basta/.virtualenvs/crass/lib/python2.7/site-packages/parsimonious/expressions.py", line 322, in _uncached_match
    node = self.members[0]._match(text, new_pos, cache, error)
  File "/home/basta/.virtualenvs/crass/lib/python2.7/site-packages/parsimonious/expressions.py", line 94, in _match
    error)
  File "/home/basta/.virtualenvs/crass/lib/python2.7/site-packages/parsimonious/expressions.py", line 252, in _uncached_match
    node = m._match(text, pos, cache, error)
  File "/home/basta/.virtualenvs/crass/lib/python2.7/site-packages/parsimonious/expressions.py", line 94, in _match
    error)
  File "/home/basta/.virtualenvs/crass/lib/python2.7/site-packages/parsimonious/expressions.py", line 252, in _uncached_match
    node = m._match(text, pos, cache, error)
  File "/home/basta/.virtualenvs/crass/lib/python2.7/site-packages/parsimonious/expressions.py", line 98, in _match
    print self, "doesn't match at", repr(text[pos:pos + 20])
  File "/home/basta/.virtualenvs/crass/lib/python2.7/site-packages/parsimonious/utils.py", line 16, in __str__
    return self.__unicode__().encode('utf-8')
  File "/home/basta/.virtualenvs/crass/lib/python2.7/site-packages/parsimonious/expressions.py", line 119, in __unicode__
    self.as_rule(),
  File "/home/basta/.virtualenvs/crass/lib/python2.7/site-packages/parsimonious/expressions.py", line 128, in as_rule
    return ((u'%s = %s' % (self.name, self._as_rhs())) if self.name else
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 3: ordinal not in range(128)
```

**Comment by lucaswiman** [comment]
I don't think this is a parse error; it can't even display the rule if it includes a non-ASCII literal or regex. I see the following error with parsimonious 0.6.2 on python 2.7:

```pytb
>>> from parsimonious.grammar import Grammar
>>> Grammar(u'ldquo = ~"\u201c"')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lucaswiman/personal/parsimonious-examples/.venv/default/lib/python2.7/site-packages/parsimonious/grammar.py", line 141, in __repr__
    return "Grammar('%s')" % str(self).encode('string_escape')
  File "/Users/lucaswiman/personal/parsimonious-examples/.venv/default/lib/python2.7/site-packages/parsimonious/utils.py", line 16, in __str__
    return self.__unicode__().encode('utf-8')
  File "/Users/lucaswiman/personal/parsimonious-examples/.venv/default/lib/python2.7/site-packages/parsimonious/grammar.py", line 137, in __unicode__
    return '\n'.join(expr.as_rule() for expr in exprs)
  File "/Users/lucaswiman/personal/parsimonious-examples/.venv/default/lib/python2.7/site-packages/parsimonious/grammar.py", line 137, in <genexpr>
    return '\n'.join(expr.as_rule() for expr in exprs)
  File "/Users/lucaswiman/personal/parsimonious-examples/.venv/default/lib/python2.7/site-packages/parsimonious/expressions.py", line 191, in as_rule
    return ((u'%s = %s' % (self.name, self._as_rhs())) if self.name else
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2: ordinal not in range(128)
>>> Grammar(u'ldquo = ~"\u201c"').default_rule.re.pattern
'\xe2\x80\x9c'
>>> Grammar(u'ldquo = "\u201c"').default_rule.literal
'\xe2\x80\x9c'
```

**Comment by Seb35** [comment]
I had issues with Unicode also with Python 2.7 (both my grammar and my string use Unicode). It was solved by using Python 3.

**Comment by mwojnars** [comment]
I'm implementing a language based on Parsimonious: https://github.com/mwojnars/hypertag

Everything works fine on Python 3, but when running with Python 2, a similar UnicodeDecodeError as reported above is raised.

```
  (...)
  File "/usr/local/lib/python2.7/dist-packages/parsimonious/grammar.py", line 115, in parse
    return self.default_rule.parse(text, pos=pos)
  File "/usr/local/lib/python2.7/dist-packages/parsimonious/expressions.py", line 120, in parse
    node = self.match(text, pos=pos)
  File "/usr/local/lib/python2.7/dist-packages/parsimonious/expressions.py", line 135, in match
    node = self.match_core(text, pos, {}, error)
  File "/usr/local/lib/python2.7/dist-packages/parsimonious/expressions.py", line 178, in match_core
    error)
  File "/usr/local/lib/python2.7/dist-packages/parsimonious/expressions.py", line 333, in _uncached_match
    node = m.match_core(text, new_pos, cache, error)
  File "/usr/local/lib/python2.7/dist-packages/parsimonious/expressions.py", line 178, in match_core
    error)
  File "/usr/local/lib/python2.7/dist-packages/parsimonious/expressions.py", line 411, in _uncached_match
    node = self.members[0].match_core(text, pos, cache, error)
  File "/usr/local/lib/python2.7/dist-packages/parsimonious/expressions.py", line 178, in match_core
    error)
  File "/usr/local/lib/python2.7/dist-packages/parsimonious/expressions.py", line 356, in _uncached_match
    node = m.match_core(text, pos, cache, error)
  File "/usr/local/lib/python2.7/dist-packages/parsimonious/expressions.py", line 178, in match_core
    error)
  File "/usr/local/lib/python2.7/dist-packages/parsimonious/expressions.py", line 356, in _uncached_match
    node = m.match_core(text, pos, cache, error)
  File "/usr/local/lib/python2.7/dist-packages/parsimonious/expressions.py", line 178, in match_core
    error)
  File "/usr/local/lib/python2.7/dist-packages/parsimonious/expressions.py", line 333, in _uncached_match
    node = m.match_core(text, new_pos, cache, error)
  File "/usr/local/lib/python2.7/dist-packages/parsimonious/expressions.py", line 178, in match_core
    error)
  File "/usr/local/lib/python2.7/dist-packages/parsimonious/expressions.py", line 238, in _uncached_match
    if text.startswith(self.literal, pos):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)
```

The line that raises the exception has `self.literal` equal:
```
'\xe2\x9d\xa8'
```
and `text` is just my input text that was passed to Grammar.parse(...) as a Unicode string. Is there any solution or workaround for this issue? The grammar can be found here:

https://github.com/mwojnars/hypertag/blob/0aa7dac507f492bb8683748ae1b5f6496410aa6c/src/hypertag/core/grammar.py

Note that several extra Unicode characters are injected before passing this grammar to Parsimonious, so both the grammar and the input text are Unicode.

**Comment by mattbasta** [comment]
I'm going to close this eight year old ticket, since python 2.7 has been completely EOL for months and I'm going into this new decade with about half the hair that I had when I filed this ticket and without github notifications about unicode errors in a dead language.

**Comment by mwojnars** [comment]
There are still people who use Python 2 for legacy reasons. Anyway, if you don't want to fix this error, you should inform on Parsimonious homepage that you do NOT support Python 2. In PyPI, there is still an information that Python 2 is supported, which is misleading. @mattbasta

**Comment by mattbasta** [comment]
@mwojnars It's my eight year old ticket, not my eight year old project. But keep in mind that you're not owed anything, especially the burden of using deprecated software whose EOL date was announced long enough ago to be in elementary school. It's asking something mighty fierce to make this code work for you in Python 2.

**Comment by lucaswiman** [comment]
@mwojnars I think your issue is different than this issue. The stack trace in the description involved displaying the rule, which I _think_ I fixed in a previous PR. It looks like your stack trace is a bug in parsing. I'd suggest opening a separate issue and moving discussion there.

I don't know whether @erikrose or the other maintainers are still actively supporting Python 2 or not. However, you've been extremely rude to @mattbasta, who correctly closed this issue and is _not a maintainer of this repository_. He wasn't misleading anyone about anything.

**Comment by mwojnars** [comment]
If @mattbasta is not a maintainer then why is he replying in the first place (my initial comment was directed to maintainers), and why is he closing a ticket that has not been resolved (it is not "his" ticket anymore when other people already commented and signalled similar problems)? When he behaves like this - which is not only rude, but also breaks the procedures on which Github's error reporting is based - he must be aware that someone else will respond appropriately.

Anyway. It seems to me that no one actually maintains this project, which is a bit of a pity, given that Parsimonious is an extremely useful tool, which I've been using myself in at least 3-4 different projects already. I don't care so much about Python 2, so as to put a "burden" on project maintainers, but I thought Python 2 was generally supported - this is what PyPI says. If fixing this issue boils down to adding a single try-except clause in one place (I don't know), or adding `from __future__ import unicode_literals` in a file header, maybe fixing it is worth doing. Otherwise, I would expect at least that a true project maintainer comments and says they will no longer support Python 2 and will not fix this issue - which is perfectly OK if that's said officially. The sole fact that a non-maintainer, like @mattbasta, does not like Python 2 and thinks everyone else should do the same, is not enough reason to ignore an issue and silently close down someone else's error reports.

I don't want to spend more time discussing this issue with non-maintainers. If a true maintainer does not show up and comment, I'm leaving this thread. In any case, I want to thank @erikrose and other authors for building this great tool. So far, I haven't found any other language generator which would be so powerful and easy to use as Parsimonious, and I think this project deserves active maintenance and development.

**Comment by lucaswiman** [comment]
> I don't want to spend more time discussing this issue with non-maintainers.

I'm not a maintainer, but I have contributed and understand the code fairly well. I can say that the stack trace you reported is a different issue than #33. As I said above, you should create a different issue reporting the problem you discovered.

**Comment by erikrose** [comment]
As the maintainer (who has been furiously looking for a deputy for some time), I can at least say that, when the next release comes out (at what time, I don't know), it'll support only Python 3. As is only too apparent, I very much need to concentrate my efforts!

**Comment by erikrose** [comment]
And thanks, @mattbasta, for making me laugh. :-) And you get one more GH notification. Muhahaha!
